 const activeStates = [
  "SUBMITTED",
  "UNDER_INITIAL_REVIEW",
  "PENDING_INFORMATION",
  "UNDER_LEGAL_REVIEW",
  "UNDER_FINANCIAL_REVIEW",
  "UNDER_REVIEW",
  "PENDING_APPROVAL",
  "APPROVED",
  "REJECTED",
];

module.exports = { activeStates };